/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package optik;

import org.junit.Test;

import static junit.framework.TestCase.assertTrue;


public class TrainTest {
    Search search = new Search();

    @Test public void testBasicOpt() {
        Train trainTest = new Train();
        float optValue = trainTest.run(5, new TestFunction());
        assertTrue((optValue >= 10.0f) && (optValue <= 20.0f));
    }

    private class TestFunction implements ITrainFunction {
        public float run() {
            return search.uniform("test1", 10.0f, 20.0f);
        }
    }
}

