/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package optik;

import org.junit.Test;

import static junit.framework.TestCase.assertTrue;


public class TrainTest {
    Search search = new Search();
    Train trainTest = new Train();

    @Test public void testUniform() {
        float optValue = trainTest.run(5, new TestUniformSearch());
        assertTrue((optValue >= 10.0f) && (optValue <= 20.0f));
    }

    @Test public void testRandInt() {
//        int optValue = (int) trainTest.run(5, new TestRandIntSearch());
//        assertTrue((optValue > 0) && (optValue < 100));
    }

    private class TestUniformSearch implements ITrainFunction {
        public float run() {
            return search.uniform("test-1", 10.0f, 20.0f);
        }
    }
}

