/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jopt;


public class Train {

    private int targetValue = 0;

    public Train() {
        this(0);
    }

    public Train(int targetValue) {
        this.targetValue = targetValue;
    }

    public int run(int turn, int data) {
        int largest = 0;
        for (int i = 0; i < turn; i++) {
            if (largest < data) {
                largest = data;
            }
        }

        return largest;
    }
}
