/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package optik;


public class Train {

    private int targetValue = 0;

    public Train() {
        this(0);
    }

    public Train(int targetValue) {
        this.targetValue = targetValue;
    }

    public float run(int turn, ITrainFunction trainFunction) {
        float largest = 0.0f;

        for (int i = 0; i < turn; i++) {
            float data = trainFunction.run();
            System.out.println("Data:" + data);
            if (largest < data) {
                largest = data;
            }
        }

        return largest;
    }
}
