/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jopt;

import org.junit.Test;
import java.util.Random;


public class TrainTest {
    Random rand = new Random();

    @Test public void testSomeLibraryMethod() {
        Train trainTest = new Train();
        trainTest.run(5, getRandomValue());
    }

    private int getRandomValue() {
        return rand.nextInt(100);
    }
}
