/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jopt;

import org.junit.Test;
import java.util.Random;


public class TrainTest {
    Random rand = new Random();
    Search search = new Search();

    @Test public void testSomeLibraryMethod() {
        Train trainTest = new Train();
        trainTest.run(5, new TestFunction());
    }

    private class TestFunction implements ITrainFunction {
        public float run() {
            return search.uniform("test1", 10.0f, 20.0f);
        }
    }
}

